Daniel
wolox-training/do-react-native pull request #1
Opened 2021-06-16 21:57 UTC by dezbrid

## Summary

[Change!] Describe your feature, problems you had, notes, improvements and others.

- se instala y configura  el Eslint
- se  modifica las funciones  de los index en las  capertas 01-spread y 02-promises  para que se ejecuten los test y estos aprueben  
## Screenshots
![imagen](https://user-images.githubusercontent.com/52224920/122299313-72820400-cec3-11eb-91f1-4c5faa40e072.png)
![imagen](https://user-images.githubusercontent.com/52224920/122299577-ca206f80-cec3-11eb-8a9b-5b5856ad7a30.png)
![imagen](https://user-images.githubusercontent.com/52224920/122299619-d6a4c800-cec3-11eb-9ee7-39fbfc000b97.png)
![imagen](https://user-images.githubusercontent.com/52224920/122298839-dbb54780-cec2-11eb-9926-c000afa9530f.png)

[Change!] Show the screenshots of the views you modified.

### Android

#### Galaxy S (or similar)

#### Pixel 2/3 (or similar)

#### Pixel 3XL (or similar)

### iOS

#### iPhone SE (or similar)

#### iPhone 6/7/8 (or similar)

#### iPhone 11/12 Base/Pro/Pro Max (or similar)

## Trello Card
[Nº 3.7] JS Stack III - ECMA 6, 7

[Change!] Link to the associated Trello card.
https://trello.com/c/ba7RB0M1/6-n-37-js-stack-iii-ecma-6-7

2021-06-16 23:09 UTC, sfernandez11 requested changes

2021-06-16 23:09 UTC, sfernandez11 commented on finger-exercises/ecmascript/package-lock.json
> +  "name": "ecmascript",
Delete this file, we use `yarn`, not `npm`

2021-06-16 23:09 UTC, sfernandez11 commented on finger-exercises/ecmascript/02-promises/index.js
>  }
You can use: `export const asyncDelay = delay;` directly

2021-06-16 23:09 UTC, sfernandez11 commented on finger-exercises/ecmascript/02-promises/index.js
> +      resolve(time);
Here you must return the `elapsedTime` between now and now + time after a `setTimeout`. In this `delay` you only return a `time` but what’s happened with the "delay" simulation?

2021-06-16 23:09 UTC, sfernandez11 commented on finger-exercises/ecmascript/.eslintrc.js
>  module.exports = {
Why changes in this file? What is the problem?

2021-06-16 23:09 UTC, sfernandez11 commented
Good work, some comments!

2021-06-17 14:26 UTC, dezbrid commented on finger-exercises/ecmascript/package-lock.json
> +  "name": "ecmascript",
ok, i will delete this file and  re install with yarn

2021-06-22 19:38 UTC, closed without merging