9.1 redux i
wolox-training/do-react-native pull request #10
Opened 2021-07-23 19:27 UTC by dezbrid

## Summary

- Install and configuration redux and reactotron 
- create store
- create action and reducer Book

## Trello Card

[Change!] Link to the associated Trello card.
https://trello.com/c/XzqSVRW5/25-n-91-redux-i-actions-reducers-store

2021-07-23 20:25 UTC, sfernandez11 requested changes
Te dejo unos comentarios pero ademas de esto, veo que esta la config de redux pero ¿y donde lo estas usando? ¿Por que agregaste algo y no lo usas?

2021-07-23 20:25 UTC, sfernandez11 commented on wbooks/package.json
> +    "@types/react-redux": "^7.1.18",
No, los `@types` son una `devDependencies`

2021-07-23 20:25 UTC, sfernandez11 commented on wbooks/src/config/ReactotronConfig.js
Este archivo deberia llamarse `reactotronConfig`, ningun archiivo que tenemos en la app se nombre con PascalCase, todos con camelCase

2021-07-23 20:25 UTC, sfernandez11 commented on wbooks/src/config/ReactotronConfig.js
> +if (__DEV__) {
No, el `if(__DEV__)` deberia cubrir toda la configuracion de reactotron

```
if (__DEV__) {
  Reactotron.configure({ name: 'wbooks' })
    .setAsyncStorageHandler(AsyncStorage)
    .useReactNative()
    .use(reactotronRedux())
    .connect();
}
```

2021-07-23 20:25 UTC, sfernandez11 commented on wbooks/src/config/ReactotronConfig.js
> +  Reactotron.clear();
No hace falta este clear

2021-07-23 20:25 UTC, sfernandez11 commented on wbooks/src/redux/book/action.ts
> +  getBooks: (newBooks: Book[]) => {
No, esto esta mal. Vos no vas a recibir la lista de libros para guardar, vas a obtener la lista de libros mediante un servicio y almacenarla en redux por lo que esta funcion no deberia recibir nada

`getBooks: () => ({ type: ActionsType.GET_BOOKS, payload: BOOKS_MOCK })`

2021-07-23 20:25 UTC, sfernandez11 commented on wbooks/src/redux/book/action.ts
> +const ActionCreators = {
asi no se nombran los objetos

2021-07-23 20:25 UTC, sfernandez11 commented on wbooks/src/redux/store.ts
> +import Reactotron from 'reactotron-react-native';
Tenes que importar el que configuraste, no el de la lib:

`import Reactotron from '@config/reactotronConfig';`

2021-07-23 20:25 UTC, sfernandez11 commented on wbooks/src/redux/store.ts
> +export const store = createStore(reducer, Reactotron.createEnhancer!());
No, `reducer` no va a ser el unico de la app por lo que deberias wrappearlo con:
```
const rootReducer = combineReducers({ book });
...
export default createStore(rootReducer, Reactotron.createEnhancer());
```

2021-07-26 16:38 UTC, dezbrid commented on wbooks/package.json
> +    "@types/react-redux": "^7.1.18",
se  retira la das dependeies  y se install en las devDependecies

2021-07-26 16:50 UTC, dezbrid commented on wbooks/src/config/ReactotronConfig.js
se corrige el nombre del archivo

2021-07-27 00:27 UTC, sfernandez11 commented on wbooks/src/config/ReactotronConfig.js
No lo cambiaste, guarda que en github a veces pasa que cambias de nombre a los archivos pero no los toma 
![image](https://user-images.githubusercontent.com/8583214/127075351-0e57a1bd-7e21-49a7-a710-72fc977d6bb5.png)

Tenes que hacer:
1) Volver para atras tu cambio localmente (o sea que tu archivo sea de nuevo `ReactotronConfig.js`)
2) Esto:
```
git mv wbooks/src/config/ReactotronConfig.js aux
git mv aux wbooks/src/config/reactotronConfig.js
```
3) Commitear y pushear

Ahi si se deberia ver reflejado

2021-07-27 00:27 UTC, sfernandez11 commented on wbooks/src/redux/store.ts
> +import Reactotron from 'reactotron-react-native';
Y este cambio que falta?

2021-07-27 00:27 UTC, sfernandez11 commented on wbooks/src/redux/store.ts
> +export const store = createStore(rootReducer, Reactotron.createEnhancer!());
La correccion está incompleta, revisalo de nuevo por favor y lee bien los comentarios de los PRs

2021-07-27 17:28 UTC, sfernandez11 commented on wbooks/App.test.tsx
> +const initialState = {};
Falta completar el initialState para que no falle el test, si no pasa el CI el PR no se mergea

2021-07-27 17:28 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/index.tsx
> +  const books = useSelector((state: State) => state.book.books);
`const books = useSelector<State, BookInterface[]>(state => state.book.books);`

2021-07-27 17:28 UTC, sfernandez11 commented on wbooks/src/redux/store.ts
> +export type State = ReturnType<typeof rootReducer>;
No, para eso esta la carpeta `interfaces`, acordate que cada archivo/carpeta tiene su proposito

2021-07-27 19:23 UTC, sfernandez11 approved these changes
🥇

2021-07-27 19:28 UTC, merged