11.2 filtro de búsqueda
wolox-training/do-react-native pull request #15
Opened 2021-08-11 23:21 UTC by dezbrid

## Summary

> 

- New screen Search
- Create a Component FilterInput in header
- Filter books 

## Screenshots

[Change!] Show the screenshots of the views you modified.

### Android

#### Galaxy S (or similar)
<img width="328" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129102157-1b184b44-c780-4c65-9560-7a5caa4f9a8f.png">

<img width="320" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129113987-4f188b6b-06f5-4aff-9fa9-893a7a800595.png">

#### Pixel 2/3 (or similar)
<img width="307" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129114376-a410b34a-cae1-4e6f-9129-bd302ed27c04.png">
<img width="299" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129114406-86d517b9-58c0-43d8-971a-5fdcf7020bc3.png">

#### Pixel 3XL (or similar)
<img width="321" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129114531-238d8dad-b7d6-4802-97be-c28328f4291d.png">
<img width="306" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129114562-1f9eb1a0-ceec-41c8-90c6-f80903b76d66.png">

### iOS

#### iPhone SE (or similar)
<img width="320" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129115217-2a03d698-d145-417e-9d06-8c605034f7f9.png">
<img width="328" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129115245-5ed64d6f-fb63-4f9a-a444-14f3862efa92.png">

#### iPhone 6/7/8 (or similar)
<img width="321" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129115556-95d1a383-82eb-47fc-b9b3-b23b959708c2.png">
<img width="308" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129115579-112b6360-24ab-43b7-8290-2d9e07816ddb.png">

#### iPhone 11/12 Base/Pro/Pro Max (or similar)
<img width="302" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129115867-71b8201d-c4c5-4d73-bae6-e6a064b43cc0.png">
<img width="330" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129115895-d79e9bce-f188-4818-8bac-0cd33659d22a.png">

## Trello Card

https://trello.com/c/EXXNOfqc/31-n-112-filtro-de-b%C3%BAsqueda

2021-08-13 14:40 UTC, sfernandez11 requested changes

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/redux/book/reducer.ts
> +    })
Acordate de que ya hay ciertas acciones creadas en `redux-recompose`, te diria que veas [onReadValue](https://github.com/Wolox/redux-recompose/tree/master/src/effects/onReadValue)

Antes de armar algun efecto custom fijate si ya no hay algo creado que te sirva para ahorrar tiempo y mejorar la implementación

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/screens/Search/components/EmptyFilter/styles.ts
> +    marginTop: 88
Para que es este margin tan grande?

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/screens/Search/components/EmptyFilter/styles.ts
> +    height: 50,
Valor repetido

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/screens/Search/components/EmptyFilter/styles.ts
> +    fontSize: 15,
El tamaño 15 para las fuentes se repite en diferentes pantallas o componentes de la App, no te parece mejor extraerlo como una constante para reutilizarlo?

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/screens/Search/index.tsx
> +import ListBooks from '@app/components/ListBooks';
`import ListBooks from '@components/ListBooks';`

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/screens/Search/index.tsx
> +  const filterSearch = useSelector<State, string>(state => state.book.filterSearch).trim();
Para que el `trim()`?

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/screens/Search/index.tsx
> +      emptyListComponent={<EmptyFilter />}
Esta pantalla tiene 2 tipos de placeholder:

* cuando el campo de busqueda  (filterSearch) esta vacio (=== '')
* cuando el resultado de la busqueda (booksFilter) esta vacio ([])

Estaria bueno cambiarle el texto dependiendo el caso, fijate como podes mejorar este componente para manejar ambos casos

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/screens/Search/index.tsx
> +      backgroundColorWhite={filterEmpty}
No, el color del fondo lo maneja la pantalla y no la lista, esto que plantas no es una buena practica (no agregar props a componentes para lo que no sea algo necesario). Esto directamente se resuelve por screen y le saca complejidad extra al componente, esta bien reutilizar codigo pero tambien hay que ver hasta que punto es necesario

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/index.tsx
> +import ListBooks from '@app/components/ListBooks';
`import ListBooks from '@components/ListBooks';`

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/index.tsx
> +  return <ListBooks books={books} />;
Quedate aca con una View o algun contenedor para el color de fondo asi la `ListBooks` no se tiene que encargar de eso

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/ListBooks/index.tsx
> +  emptyListComponent?: JSX.Element | null;
En que caso es `null`? Yo solo veo un Element o undefined, no null

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/ListBooks/index.tsx
> +  backgroundColorWhite?: boolean | null;
Borrar y sacar la logica asociada a esta prop

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +import Search from '@app/screens/Search';
`import Search from '@screens/Search';`

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +          headerLeft: () => null
Si bien en el Marvel no aparece la flecha, si la eliminas, como hace el usuario para volver para atras?

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/HeaderSearchButton/index.tsx
> +  };
Dejarla en 1 linea, no hacen falta los `{}`

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    height: 12,
Hacela cuadrada y extrae la constante (12) para poder reutilizarla

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    marginRight: 13,
Siempre trata de poner los estilos de la forma mas optimizada posible, por ejemplo aca:
```ts
margin: 8,
marginRight: 13,
```

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    height: 28,
Al volver a agregar la backArrow del header seguro que tengas que ahicarle un poco el ancho para que entren ambas cosas

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    paddingVertical: 6,
En vez de agregar padding horizontal o vertical en cada uno de los componentes internos es mejor aplicarselo directamente al container

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    height: 14,
Repetido

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    right: 8,
Por que `right` y no `marginRight`? Igual haciendo el cambio de tener esto en el contendor ya no hace falta aca

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/FilterInput/index.tsx
> +  };
1 linea

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/FilterInput/index.tsx
> +  }, [dispatch, bookFilter]);
Mal planteada la logica, revisarlo de nuevo y hacer los cambios necesarios. Estas guardando informacion en el componente (useState) que ya se puede guardar directamente en redux, ademas el almacenamiento del valor en redux se tiene que hacer con el `onChangeText` del TextInput y no con un useEffect

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/FilterInput/index.tsx
> +      <Image source={icSearch} style={styles.imageSearch} />
Falta el `resizeMode`

2021-08-13 14:40 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/FilterInput/index.tsx
> +      <TextInput value={bookFilter} onChangeText={text => setBookFilter(text)} style={styles.input} />
2 cosas con el `onChangeText`:

* Como te puse mas arriba, esto deberia dispatchear el valor para almacenarlo en redux en vez de en un state local
* Cuando tenes funciones que usan el mismo parametro que reciben (pasamanos) no hace falta esta declaracion `onChangeText={text => setBookFilter(text)}` sino que directamente se puede usar `onChangeText={setBookFilter}`

2021-08-13 17:09 UTC, dezbrid commented on wbooks/src/app/screens/Search/components/EmptyFilter/styles.ts
> +    marginTop: 88
ese es un  especificacion que esta en marvel 

<img width="409" alt="imagen" src="https://user-images.githubusercontent.com/52224920/129394989-b86e6459-2d8d-4d0c-9b90-c574f21466d4.png">

2021-08-13 17:27 UTC, dezbrid commented on wbooks/src/app/screens/Search/components/EmptyFilter/styles.ts
> +    fontSize: 15,
se crea un nuevo archivo de constante global sizes con lo valores regularText =15  y titleText=17( se encontro este valor repetido )

2021-08-13 17:29 UTC, dezbrid commented on wbooks/src/app/screens/Search/index.tsx
> +import ListBooks from '@app/components/ListBooks';
corregido

2021-08-13 18:02 UTC, dezbrid commented on wbooks/src/app/screens/Search/index.tsx
> +  const filterSearch = useSelector<State, string>(state => state.book.filterSearch).trim();
lo uso  para evitar la busqueda  con un espacio

2021-08-13 20:33 UTC, dezbrid commented on wbooks/src/app/screens/Library/index.tsx
> +import ListBooks from '@app/components/ListBooks';
corregido

2021-08-13 20:35 UTC, dezbrid commented on wbooks/src/app/screens/Search/index.tsx
> +      backgroundColorWhite={filterEmpty}
se dejoe el componente solo con la lista , cada  vista tendra su contenedor SafeAreaView

2021-08-13 20:35 UTC, dezbrid commented on wbooks/src/app/screens/Library/index.tsx
> +  return <ListBooks books={books} />;
corregido

2021-08-13 20:35 UTC, dezbrid commented on wbooks/src/app/components/ListBooks/index.tsx
> +  emptyListComponent?: JSX.Element | null;
se corrigio

2021-08-13 20:36 UTC, dezbrid commented on wbooks/src/app/components/ListBooks/index.tsx
> +  backgroundColorWhite?: boolean | null;
se corrigio

2021-08-13 20:38 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +import Search from '@app/screens/Search';
corregido

2021-08-13 20:39 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +          headerLeft: () => null
se   deja el  boton de regresar

2021-08-13 20:41 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/components/HeaderSearchButton/index.tsx
> +  };
se corrige

2021-08-13 20:44 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    height: 12,
corregido

2021-08-13 20:45 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    marginRight: 13,
se realiza el cambio

2021-08-13 20:55 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    height: 14,
se crea la constante

2021-08-13 20:56 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/components/FilterInput/index.tsx
> +  };
corregido

2021-08-13 20:57 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/components/FilterInput/index.tsx
> +      <Image source={icSearch} style={styles.imageSearch} />
corregido

2021-08-14 01:52 UTC, dezbrid commented on wbooks/src/redux/book/reducer.ts
> +    })
se  realiza el cambio

2021-08-14 01:53 UTC, dezbrid commented on wbooks/src/app/screens/Search/components/EmptyFilter/styles.ts
> +    height: 50,
se realiza una constante

2021-08-14 02:43 UTC, dezbrid commented on wbooks/src/app/screens/Search/index.tsx
> +      emptyListComponent={<EmptyFilter />}
se amplia el comportamientamiento

2021-08-16 01:58 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    right: 8,
se  realizo cambio en el container

2021-08-16 01:58 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/components/FilterInput/index.tsx
> +  }, [dispatch, bookFilter]);
se deja solo con redux

2021-08-16 01:59 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/components/FilterInput/index.tsx
> +      <TextInput value={bookFilter} onChangeText={text => setBookFilter(text)} style={styles.input} />
corregido

2021-08-16 02:00 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    marginRight: 13,
se  realizo cambio en el container

2021-08-16 02:00 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    paddingVertical: 6,
se aplico el  padding 8 en el container

2021-08-19 14:28 UTC, sfernandez11 reviewed
Ultimos comentarios

2021-08-19 14:28 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/FilterInput/index.tsx
> +  const handleOnChangesText = (text: string) => dispatch(BookAction.filterBooks(text));
El patron que usamos para los nombres de las funciones es:
* handleAction (reemplazando `Action` por la acción que se está realizando) => Esto al momento de declarar la funcion
* onAction (reemplazando `Action` por la acción que se está realizando) => Esto al momento de usar la funcion

Un ejemplo seria:
```ts
const handlePress = () => { ... };
...
<Component onPress={handlePress} />
```

Pero en este caso estas haciendo `handleOnChangesText` o sea agregando ambas cosas y deberia ser:
```ts
<TextInput value={filterSearch} onChangeText={handleChangesText} style={styles.input} />
```

2021-08-19 14:28 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/FilterInput/styles.ts
> +    marginVertical: -12,
**NUNCA** usar margenes o paddings negativos, no esta bien conceptualmente tener una distancia negativa, si necesitas mover un elemento acordate que tenes `top`, `bottom`, `left` y `right`

2021-08-19 14:28 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/styles.ts
> +    marginLeft: -22
**NUNCA** usar margenes o paddings negativos, no esta bien conceptualmente tener una distancia negativa, si necesitas mover un elemento acordate que tenes `top`, `bottom`, `left` y `right`

2021-08-19 14:28 UTC, sfernandez11 commented on wbooks/src/app/screens/Search/components/EmptyFilter/index.tsx
> +  const doNotFound = 'Search Do Not Found';
¿Por qué hay constantes dentro de la declaracion de la funcion? Hace falta que se vuelva a crear en cada render? Ademas, constantes en MAYUS

2021-08-19 14:28 UTC, sfernandez11 commented on wbooks/src/constants/sizes.ts
> +  titleText: 17
constantes en MAYUS, ademas si ya estamos hablado de SIZES para fuentes no hace falta aclarar el `text` (redundante)

2021-08-19 21:18 UTC, sfernandez11 approved these changes
🥇

2021-08-19 21:22 UTC, merged