6.1 componente libro
wolox-training/do-react-native pull request #5
Opened 2021-06-24 19:08 UTC by dezbrid

## Summary

> 

- Create component Book

## Screenshots

<img width="877" alt="imagen" src="https://user-images.githubusercontent.com/52224920/123318707-218e9300-d4f5-11eb-85c8-591d515e049d.png">
<img width="626" alt="imagen" src="https://user-images.githubusercontent.com/52224920/123318810-3ec36180-d4f5-11eb-8ee5-3164c9ffc276.png">
<img width="537" alt="imagen" src="https://user-images.githubusercontent.com/52224920/123318861-4be05080-d4f5-11eb-8496-22edc6076100.png">

## Trello Card

https://trello.com/c/goyRIV2z/10-n-61-componente-libro

2021-06-25 16:04 UTC, sfernandez11 requested changes
Good work, some comments!

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/constants/colors.ts
> +  textColor: '#4A4A4A'
En general tratamos de usar el verdadero nombre del color => https://chir.ag/projects/name-that-color

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/app/components/Book/styles.ts
> +}
No hace falta agregar una interfaz para los estilos

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/app/components/Book/styles.ts
> +    height: 90,
No uses tamaños fijos NUNCA, solo para imagenes o cosas especificas. Para adaptar componentes usa "margin" y "padding" => En este caso ya estas usando padding entonces esto no hace falta

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/app/components/Book/styles.ts
> +    height: 60
y el ancho? Ademas, si es el mismo valor extrae 60 como constante dentro de este archivo

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/app/components/Book/styles.ts
> +    flexDirection: 'column',
Es el default

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/app/components/Book/styles.ts
> +    textAlign: 'left',
Es el default

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/app/components/Book/styles.ts
> +    textAlign: 'left',
Es el default

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/app/components/Book/index.tsx
> +}
Extrae esto en un archivo dentro de la carpeta `@interfaces` que para eso está

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/app/components/Book/index.tsx
> +  item: Item;
Esto es un book: Book, no un item

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/app/components/Book/index.tsx
> +interface Item {
Book

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/app/components/Book/index.tsx
> +  imageUrl: String | null;
Mal, los nombres de cada interfaz (hablando de las nativas de JS) son en minuscula => Solo las que armamos por default nosotros son capitalizadas

String => string
Number => number

String y Number son clases de JS

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/app/components/Book/index.tsx
> +        source={item.imageUrl ? { uri: item.imageUrl } : require('@assets/img_book_placeholder.png')}
No usamos in-line require, cambialo por un import mas arriba:
```
import placeholder from '@assets/img_book_placeholder.png';
```

2021-06-25 16:04 UTC, sfernandez11 commented on wbooks/src/app/components/Book/index.tsx
> +        <Text style={styles.author}>{item.author}</Text>
En vez de estar accediendo a cada elemento => `item.XXX`, `item.YYY`, etc... podes aplicar el destructuring de props que aprendiste en la card anterior:
```
const { imageUrl, title, etc... } = book;
```

2021-06-26 15:45 UTC, dezbrid commented on wbooks/src/app/components/Book/styles.ts
> +}
se  retiro el interface

2021-06-26 15:48 UTC, dezbrid commented on wbooks/src/constants/colors.ts
> +  textColor: '#4A4A4A'
se agregaron los nombres  verdaderos para white y textColor,  el nombe verdadero de #0d0d0d es Cod Gray, el cual no me fue aceptado por RN deje el HEX

2021-06-26 15:48 UTC, dezbrid commented on wbooks/src/app/components/Book/styles.ts
> +    height: 90,
se retiro el tamaño de la card

2021-06-26 15:49 UTC, dezbrid commented on wbooks/src/app/components/Book/styles.ts
> +    height: 60
se agrege una constante con los valores del ancho y el alto

2021-06-26 15:49 UTC, dezbrid commented on wbooks/src/app/components/Book/styles.ts
> +    flexDirection: 'column',
se retiro     flexDirection: 'column',

2021-06-26 15:50 UTC, dezbrid commented on wbooks/src/app/components/Book/styles.ts
> +    textAlign: 'left',
se retiro  textAlign: 'left',

2021-06-26 15:50 UTC, dezbrid commented on wbooks/src/app/components/Book/styles.ts
> +    textAlign: 'left',
se retiro  textAlign: 'left',

2021-06-26 15:51 UTC, dezbrid commented on wbooks/src/app/components/Book/index.tsx
> +  item: Item;
se remplaza a book: Book

2021-06-26 15:52 UTC, dezbrid commented on wbooks/src/app/components/Book/index.tsx
> +interface Item {
se remplazo

2021-06-26 15:52 UTC, dezbrid commented on wbooks/src/app/components/Book/index.tsx
> +  imageUrl: String | null;
se realizo la correcion

2021-06-26 15:53 UTC, dezbrid commented on wbooks/src/app/components/Book/index.tsx
> +        source={item.imageUrl ? { uri: item.imageUrl } : require('@assets/img_book_placeholder.png')}
se realiza la correcion planteada

2021-06-26 15:53 UTC, dezbrid commented on wbooks/src/app/components/Book/index.tsx
> +        <Text style={styles.author}>{item.author}</Text>
se realiza el destructuring

2021-06-26 16:00 UTC, dezbrid commented on wbooks/src/app/components/Book/index.tsx
> +}
se extrae la  interfaces  y se agrega a @interfaces

2021-06-27 21:09 UTC, dezbrid commented on wbooks/src/constants/colors.ts
> +  textColor: '#4A4A4A'
se  agrega los nombres verdaderos

2021-06-28 20:53 UTC, sfernandez11 commented on wbooks/src/app/components/Book/index.tsx
> +import { Book as BookInterfaces } from '@interfaces/index';
2 cosas aca:
* `BookInterfaces` => `BookInterface` es singular, no plural
* `@interfaces/index` mal => `@interfaces/book`, usa un archivo para extraer interfaces de componentes o flujos de la App

2021-06-28 20:53 UTC, sfernandez11 commented on wbooks/src/app/components/Book/index.tsx
> +        source={imageUrl ? { uri: imageUrl as string } : placeholder}
No hace falta el `as string`, para eso ya está la interfaz

2021-06-28 20:53 UTC, sfernandez11 commented on wbooks/src/app/components/Book/styles.ts
> +    width: SIZES.imagenBookLibary.width
No hace falta crear un archivo para esto, cuando digo extraer en constante/s es dentro de este mismo archivo. Solo deberias crear un archivo dentro de la carpeta `@constants` cuando sean constantes que se usan en diferentes lugares de la app como los colores

2021-06-28 20:53 UTC, sfernandez11 commented on wbooks/src/app/components/Book/styles.ts
> +    flex: 1,
Hace falta este `flex: 1`?

2021-06-28 20:53 UTC, sfernandez11 commented on wbooks/src/app/components/Book/styles.ts
> +    flex: 3,
Si no agregas el `flex: 1` en el anterior y aca pones `flex: 1` deberia funcionar bien

2021-06-28 20:53 UTC, sfernandez11 commented on wbooks/src/constants/colors.ts
> +  codGray: '#0d0d0d',
Hexadecimal en MAYUS => `#0D0D0D`

2021-06-28 20:53 UTC, sfernandez11 commented on wbooks/src/constants/sizes.ts
> +};
No hace falta, borrarlo

2021-06-28 22:16 UTC, sfernandez11 approved these changes
🥇

2021-06-28 22:20 UTC, merged