6.2 lista de libros
wolox-training/do-react-native pull request #6
Opened 2021-06-29 00:04 UTC by dezbrid

## Summary

> 

- Create screen Library
- the Book component moves within the  Library screen
- implementation the FlatList's component
- the list of books is displayed

## Screenshots

### Android

#### Galaxy S (or similar)
<img width="415" alt="Captura de Pantalla 2021-06-28 a la(s) 6 01 58 p  m" src="https://user-images.githubusercontent.com/52224920/123714970-fd0c2100-d83c-11eb-906a-96f9710835d8.png">

#### Pixel 2/3 (or similar)
<img width="399" alt="Captura de Pantalla 2021-06-28 a la(s) 5 59 11 p  m" src="https://user-images.githubusercontent.com/52224920/123714980-03020200-d83d-11eb-9157-779cf720dd31.png">

#### Pixel 3XL (or similar)
<img width="440" alt="Captura de Pantalla 2021-06-28 a la(s) 5 56 52 p  m" src="https://user-images.githubusercontent.com/52224920/123714992-07c6b600-d83d-11eb-8a42-f55981ed2fba.png">

### iOS

#### iPhone SE (or similar)
<img width="492" alt="Captura de Pantalla 2021-06-28 a la(s) 5 54 31 p  m" src="https://user-images.githubusercontent.com/52224920/123715017-144b0e80-d83d-11eb-9081-380eb8565f1a.png">

#### iPhone 6/7/8 (or similar)
<img width="493" alt="Captura de Pantalla 2021-06-28 a la(s) 5 42 36 p  m" src="https://user-images.githubusercontent.com/52224920/123715053-23ca5780-d83d-11eb-89b2-ad1a77f68d40.png">

#### iPhone 11/12 Base/Pro/Pro Max (or similar)
<img width="480" alt="Captura de Pantalla 2021-06-28 a la(s) 5 35 44 p  m" src="https://user-images.githubusercontent.com/52224920/123715062-288f0b80-d83d-11eb-8a7a-1cf6686f71d8.png">

## Trello Card

https://trello.com/c/0DctWGOD/9-n-62-lista-de-libros

2021-06-29 22:27 UTC, sfernandez11 requested changes

2021-06-29 22:27 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +  const titleWithoutSpaces = title.replace(/\s/, '');
Si ya estas usando el `trim()`, ¿para qué esto?

2021-06-29 22:27 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/components/Book/styles.ts
> +const WIDTH_IMAGE = 55;
Si en Marvel es de: 60 x 40, ¿por qué usaste 90 x 55?
![image](https://user-images.githubusercontent.com/8583214/123874976-4c228680-d90f-11eb-9545-fd9bcf61b9c2.png)

2021-06-29 22:27 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/index.tsx
> +        ItemSeparatorComponent={() => <View style={styles.separator} />}
??? No hay ningun separador en la lista de libros, es solo un `marginBottom: 10` 🤔

2021-06-29 22:27 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/index.tsx
> +        renderItem={({ item }) => <Book book={item} />}
Extraer como arrow function dentro de la funcion `Library`

2021-06-29 22:27 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/index.tsx
> +        keyExtractor={item => item.id.toString()}
Extraer como arrow function dentro de la funcion `Library`

2021-06-29 22:27 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/index.tsx
> +        ListFooterComponent={() => <View />}
No le veo el punto sinceramente, ¿para qué?

2021-06-29 22:27 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/index.tsx
> +        ListFooterComponentStyle={styles.footer}
Lo mismo, tenes que usar los estilos de la lista. No crees componentes y le pongas estilos cuando podes usar `style` o `contentContainerStyle`. Aca si le pones a cada libro: `marginBottom: 10` si le sumas a la lista un `paddingBottom: 20` es lo mismo y mejor

2021-06-29 22:27 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/styles.ts
> +  }
Borrar y mejorar estilos

2021-06-30 17:42 UTC, dezbrid commented on wbooks/src/app/screens/Library/index.tsx
> +        ItemSeparatorComponent={() => <View style={styles.separator} />}
se elimina el separador y se agrega el marign

2021-06-30 17:43 UTC, dezbrid commented on wbooks/src/app/screens/Library/index.tsx
> +        renderItem={({ item }) => <Book book={item} />}
se extrae como arrow fuction

2021-06-30 17:44 UTC, dezbrid commented on wbooks/src/app/screens/Library/index.tsx
> +        ListFooterComponentStyle={styles.footer}
se cambia el style por contenteContainerStyle  y se aplica  em paddingBottim

2021-06-30 17:45 UTC, dezbrid commented on wbooks/src/app/screens/Library/index.tsx
> +        ListFooterComponent={() => <View />}
se elimina y se aplica el estilo correpondiente  al Flatlist

2021-06-30 17:46 UTC, dezbrid commented on wbooks/src/app/screens/Library/styles.ts
> +  }
se corrige los estilos

2021-06-30 17:50 UTC, dezbrid commented on wbooks/src/app/screens/Library/index.tsx
> +        keyExtractor={item => item.id.toString()}
se extrae como arrow function

2021-06-30 17:51 UTC, dezbrid commented on wbooks/src/app/screens/Library/components/Book/styles.ts
> +const WIDTH_IMAGE = 55;
se cambia los tamaños  a los de marvel

2021-06-30 17:59 UTC, dezbrid commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +  const titleWithoutSpaces = title.replace(/\s/, '');
en prueba anterior no me borraba un espacio con el .trim(), ahora lo cheque de nuevo si funciono bien. Se retira  el replace

2021-06-30 19:03 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/index.tsx
> +  const renderItem = ({ item }: { item: BookInterface }) => <Book book={item} />;
Podes usar la interfaz `ListRenderItem` de `react-native` para mejorar esto:

```
const renderItem: ListRenderItem<BookInterface> = ({ item }) => <Book book={item} />;
```

2021-06-30 19:03 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/styles.ts
> +    paddingTop: 17
¿Para que usas paddingVertical si despues lo pisas con el paddingTop?
```
paddingBottom: 20,
paddingTop: 17
```

2021-06-30 19:54 UTC, sfernandez11 approved these changes
🥇

2021-06-30 20:03 UTC, merged