7.1 react navigation
wolox-training/do-react-native pull request #7
Opened 2021-07-02 00:20 UTC by dezbrid

## Summary

> 
- installation and confguration  React Navigation
- modified book component, TouchableNativeFeedback was added with function to navigate to screen Book Detail
- created new screen  Book Detail

## Screenshots

### Android

#### Galaxy S (or similar)
<img width="444" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124202283-a0f50700-da9f-11eb-9e99-c02c55390472.png">

#### Pixel 2/3 (or similar)
<img width="432" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124202564-36909680-daa0-11eb-8c64-e6de4e65379e.png">

#### Pixel 3XL (or similar)
<img width="427" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124202652-6d66ac80-daa0-11eb-8661-67f41874baab.png">

### iOS

#### iPhone SE (or similar)
<img width="468" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124202947-33e27100-daa1-11eb-8e13-d3b03ef7439b.png">

#### iPhone 6/7/8 (or similar)
<img width="444" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124202828-e5cd6d80-daa0-11eb-838c-ad1c03fa112c.png">

#### iPhone 11/12 Base/Pro/Pro Max (or similar)
<img width="495" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124202710-971fd380-daa0-11eb-9c80-068a3f312daa.png">

## Trello Card

https://trello.com/c/mQqhQZkq/13-n-71-introducci%C3%B3n-a-react-navigation

2021-07-02 19:58 UTC, sfernandez11 requested changes

2021-07-02 19:58 UTC, sfernandez11 commented on wbooks/App.tsx
> +import 'react-native-gesture-handler';
Este deberia ser el 1er import de todos en este archivo

2021-07-02 19:58 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +    <Stack.Navigator initialRouteName={Routes.libraryListRoute} headerMode="screen">
* ¿por qué `headerMode="screen"` ?
* El header se maneja a nivel stack, no a nivel screen

2021-07-02 19:58 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +      <Stack.Screen name={Routes.libraryListRoute} component={Library} options={{ headerShown: false }} />
2 cosas aca:

* ¿por qué `headerShown: false`?
* ¿Y el `TITLE`?

2021-07-02 19:58 UTC, sfernandez11 commented on wbooks/src/app/index.tsx
> +    </NavigationContainer>
Falta el `StatusBar` como children de `NavigationContainer` o sea al mismo nivel de `AppNavigator`

2021-07-02 19:58 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +import { useNavigation } from '@react-navigation/native';
Este es un import global, no un alias local => Ordenar

2021-07-02 19:58 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +  function handleOpenBookDetail() {
No, dentro de una funcion declaramos arrow functions, no mas functions

2021-07-02 19:58 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +    navigation.navigate('BookDetail', { book });
Usar una constante para las Routes de la App

2021-07-02 19:58 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +    <TouchableNativeFeedback onPress={handleOpenBookDetail}>
Por que este elemento? Usa `TouchableOpacity` que es el que usamos generalmente

2021-07-02 19:58 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +      <View style={styles.container}>
¿Para que dejaste este View si ya le podes pasar el style al elemento padre y borrar este? Guarda con crear una estructura con contenedores innecesarios

2021-07-02 19:58 UTC, sfernandez11 commented on wbooks/src/constants/routes.ts
> +  bookDetailListRoute: 'BookDetail'
Acomoda estos nombres por favor, siempre que sean lo mas claro posible:
```
libraryListRoute => Library,
bookDetailListRoute => BookDetail
```

2021-07-06 14:38 UTC, dezbrid commented on wbooks/App.tsx
> +import 'react-native-gesture-handler';
corregido

2021-07-06 14:49 UTC, dezbrid commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +  function handleOpenBookDetail() {
se remplaza la  funcion

2021-07-06 14:55 UTC, dezbrid commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +    navigation.navigate('BookDetail', { book });
se usa las constantes

2021-07-06 18:57 UTC, sfernandez11 approved these changes
🥇

2021-07-06 19:07 UTC, merged