7.4 header
wolox-training/do-react-native pull request #8
Opened 2021-07-06 20:33 UTC by dezbrid

## Summary

> 

- add assets for header and icons
-  configuration the custom header 

## Screenshots

### Android

#### Galaxy S (or similar)
<img width="434" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124661864-b5ede380-de6d-11eb-8f26-d11e59cffb44.png">
<img width="482" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124661907-c1d9a580-de6d-11eb-82d6-7ed6dea9bebb.png">

#### Pixel 2/3 (or similar)
<img width="449" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124661708-7cb57380-de6d-11eb-9640-d648049302cd.png">
<img width="423" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124661747-89d26280-de6d-11eb-9ab5-8566cb48f543.png">

#### Pixel 3XL (or similar)
<img width="431" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124661533-3b24c880-de6d-11eb-8752-74fe731387f6.png">
<img width="432" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124661571-4c6dd500-de6d-11eb-8bda-34b6059b1518.png">

### iOS

#### iPhone SE (or similar)
<img width="479" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124660941-7d013f00-de6c-11eb-994a-fecd9394410d.png">
<img width="490" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124660981-87bbd400-de6c-11eb-90ac-242e711bf734.png">

#### iPhone 6/7/8 (or similar)
<img width="474" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124660444-cf8e2b80-de6b-11eb-9d0b-b48913262d9d.png">
<img width="454" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124662306-40364780-de6e-11eb-88ca-ab1636217431.png">

#### iPhone 11/12 Base/Pro/Pro Max (or similar)
<img width="508" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124659991-3a8b3280-de6b-11eb-9597-f3ef5b8a9b68.png">
<img width="513" alt="imagen" src="https://user-images.githubusercontent.com/52224920/124660094-5c84b500-de6b-11eb-93fa-cdfc9147d2b5.png">

## Trello Card
https://trello.com/c/naNAh8c5/15-n-74-header

2021-07-06 23:30 UTC, sfernandez11 requested changes

2021-07-06 23:30 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +import headerSearch from './assets/ic_search.png';
Estos iconos no se piden, solo el `headerBackImage` y el `headerImage`

2021-07-06 23:30 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +        headerTitleAlign: 'center'
No, siempre respetar la navegación nativa: 
* En Android el titulo va tirado a la izquierda
* En iOS en el centro

Asi nos manejamos generalmente en los proyectos a menos que el cliente indique lo contrario (lo mismo pasa con la backImage pero para el training es un caso especial para practicarlo nada mas)

2021-07-06 23:30 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +        headerTintColor: COLORS.white,
Agregar mas altura al header, queda muy pegado al titulo y chiquito respecto a Marvel. Ademas, ¿y el `headerTitleStyle`?

2021-07-06 23:30 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +          headerRight: () => <Image source={headerSearch} style={styles.headerIcons} />
No son necesarios por ahora

2021-07-06 23:30 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +          )
No, esto se hace desde el `screenOptions` del stack y se maneja automaticamente. Agregar `headerBackTitleVisible: false,` para que no se vea la ruta a la que vuelve

2021-07-08 14:43 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +import headerSearch from './assets/ic_search.png';
se retiraron

2021-07-08 14:44 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +        headerTitleAlign: 'center'
se retiro  la prop headerTitleAlign

2021-07-08 14:44 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +        headerTintColor: COLORS.white,
e agrego mas altura al header 115

2021-07-08 14:44 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +          headerRight: () => <Image source={headerSearch} style={styles.headerIcons} />
se retiro

2021-07-08 14:45 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +          )
se modifico

2021-07-08 19:50 UTC, sfernandez11 reviewed
Ultimos comentarios, ademas borrate estos 3 assets que no se van a usar 

<img width="722" alt="Captura de Pantalla 2021-07-08 a la(s) 16 47 09" src="https://user-images.githubusercontent.com/8583214/124981723-46fac100-e00c-11eb-8011-c568c7f84728.png">

2021-07-08 19:50 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/styles.ts
> +    marginHorizontal: 13
¿Por que al titulo y no al contenedor? Porque sino lo estas repitiendo para esto y para el icono de la flecha para atras tambien

2021-07-08 19:50 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/styles.ts
> +    flex: 1
Hace falta esto? De ultima agrega: ` height: '100%',` pero el flex es innecesario

2021-07-08 19:50 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +          headerBackImage: () => <Image source={headerBackImage} style={styles.headerIcons} />
Esto sigue mal, las configuraciones van en el stack, solo los casos particulares va por screen

2021-07-08 19:50 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/styles.ts
> +    marginBottom: 20
Revisar si hace falta esto cuando saques el `flex: 1`

2021-07-09 16:03 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/styles.ts
> +    marginHorizontal: 13
en el headerStyle no haces efecto  los margin o padding

2021-07-09 16:04 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/styles.ts
> +    flex: 1
se retiro el  flex 1 se deja height : '100%'

2021-07-09 16:05 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +          headerBackImage: () => <Image source={headerBackImage} style={styles.headerIcons} />
se  deja el headerBackImage en el Satck

2021-07-09 16:06 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/styles.ts
> +    marginBottom: 20
sigue siendo necesarios , se ordeno de otra forma el estilo para no repetirlo

2021-07-12 21:12 UTC, sfernandez11 reviewed
Agrego un comentario y te quedó uno mas anterior por aplicar (revisar bien por favor)

2021-07-12 21:12 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/styles.ts
> +    fontWeight: 'normal'
Y el resto?

2021-07-12 23:00 UTC, sfernandez11 approved these changes
🥇

2021-07-12 23:00 UTC, merged