8 tab bar
wolox-training/do-react-native pull request #9
Opened 2021-07-13 15:28 UTC by dezbrid

## Summary

> 

- add asset to  tab bar
- install and configuration tab bar 

## Screenshots

### Android

#### Galaxy S (or similar)
<img width="398" alt="imagen" src="https://user-images.githubusercontent.com/52224920/125477547-acb7ea6a-f7e7-4b1f-a327-1ec7d2e45792.png">

#### Pixel 2/3 (or similar)
<img width="378" alt="imagen" src="https://user-images.githubusercontent.com/52224920/125477772-2c9db9e7-8093-4000-a48c-0e13bedd34e1.png">

#### Pixel 3XL (or similar)
<img width="428" alt="imagen" src="https://user-images.githubusercontent.com/52224920/125478212-78d890e1-463e-42f8-a2ca-0fb058571160.png">

### iOS

#### iPhone SE (or similar)
<img width="441" alt="imagen" src="https://user-images.githubusercontent.com/52224920/125479083-40c5413a-fb44-4b88-8ee4-08d4ab8d8364.png">

#### iPhone 6/7/8 (or similar)
<img width="426" alt="imagen" src="https://user-images.githubusercontent.com/52224920/125479720-090242e3-b588-4eb8-ba78-069a55b7de96.png">

#### iPhone 11/12 Base/Pro/Pro Max (or similar)
<img width="448" alt="imagen" src="https://user-images.githubusercontent.com/52224920/125479800-f89b4383-386e-49f8-99a8-3f57537c660c.png">

## Trello Card

https://trello.com/c/WPFnm5hH/18-n-8-tab-bar

2021-07-15 01:01 UTC, sfernandez11 requested changes
Por favor revisar la implementacion y volver a leer la teoria que se indica de React Navigation ya que varias cosas no quedaron bien

2021-07-15 01:01 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +const Tab = createBottomTabNavigator();
Muchas constantes y codigo repetido en 1 solo archivo, necesita un buen refactor

2021-07-15 01:01 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +const StackWishList = () => {
* 1ro estas reptiendo el mismo objeto del header en todas las pantallas
* 2do se pedian solo 2 tabs, no todas aunque tampoco esta mal, fijate como lo podes optimizar todo esto
* 3ro si una tab solo tiene 1 screen se puede usar directamente, no hace falta crear un stack para esto (no pasa nada que no tenga el mismo header)

2021-07-15 01:01 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +};
No meter todo dentro de 1 solo archivo

2021-07-15 01:01 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +};
Lo mismo

2021-07-15 01:01 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +        options={{
Mal, por que las options a nivel tab y no a nivel TabNavigator?

2021-07-15 01:01 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +            return <Image source={focused ? icLibraryActive : icLibrary} />;
¿Por que repetis lo mismo en todas las tabs en vez de extraer comportamiento en un componente?

2021-07-15 01:01 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +    <Stack.Navigator
Mal todo aca tambien, ahora el AppNavigator es el TabNavigator, ¿por qué dejaste un stack?

ademas, si BookDetail solo se puede acceder desde Library, ¿por qué esta aca definida?

2021-07-21 20:20 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +const Tab = createBottomTabNavigator();
se movio la constante TITLES al archivo  routes dentrode la carpeta constants

2021-07-21 20:21 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +const StackWishList = () => {
se realiza los cambios

2021-07-21 20:21 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +};
se movio  de lugar

2021-07-21 20:21 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +        options={{
se organiza las opciones en  el TabNavigator

2021-07-21 20:22 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +            return <Image source={focused ? icLibraryActive : icLibrary} />;
se corrigio

2021-07-21 20:22 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +    <Stack.Navigator
se realizo el cambio

2021-07-21 23:45 UTC, sfernandez11 reviewed
Ultimos comentarios

2021-07-21 23:45 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +const tabBarIcon = createBottomTabNavigator();
Por qué `tabBarIcon`? Usa `Tab` or `TabNavigator`? Ademas, los componentes no van en camelCase, van en PascalCase

2021-07-21 23:45 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +};
Y este comentario? Esto sigue aca colgado en vez de ser una screen o componente, aca no va

2021-07-21 23:45 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +const StackNavigator = () => {
No te olvides de ser descriptivo con las constantes que usas, `StackNavigator` es muy generico, por que no `LibraryStack`? O algo que indique de qué es el stack que estas armando

2021-07-21 23:45 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +        tabBarIcon: ({ focused }) => {
Y el componente que tenias que extraer? Creo que habiamos hablado de esto ya

2021-07-21 23:45 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/index.tsx
> +      }}>
Y los estilos del texto? Acordate de revisar bien el Marvel sino despues las funcionalidades no pasan QA y te las rechazan por estas diferentes visualmente

2021-07-23 15:58 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +};
se extrajo el EmptyScreen del  achivo

2021-07-23 15:59 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +const tabBarIcon = createBottomTabNavigator();
se corrige

2021-07-23 15:59 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +const StackNavigator = () => {
se cambia el nombre

2021-07-23 15:59 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +        tabBarIcon: ({ focused }) => {
se realiza un componente

2021-07-23 16:00 UTC, dezbrid commented on wbooks/src/app/components/AppNavigator/index.tsx
> +      }}>
se agrega los estilos de  marvel para los labels

2021-07-23 20:10 UTC, sfernandez11 commented on wbooks/App.tsx
> +import '@config/ReactotronConfig';
¿Por qué este cambio? No lo entiendo

2021-07-23 20:10 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/TabBarIcons/index.tsx
> +import icLibraryActive from '../../assets/ToolBar/ic_library_active.png';
Mala ubicación de los assets. Si se usa solo en este componente, ¿por que no estan a este nivel directamente?

Ademas, eliminar los assets de ToolBar que no se utilicen mas

2021-07-23 20:10 UTC, sfernandez11 commented on wbooks/src/app/components/AppNavigator/components/TabBarIcons/index.tsx
> +function TabBarIcons({ route, focused }: Props) {
TabBarIcons => ¿por qué `IconS`??? Este componente renderea solo 1 icono, no varios

Cuidado con los nombres

2021-07-23 20:13 UTC, dezbrid commented on wbooks/App.tsx
> +import '@config/ReactotronConfig';
esto  fue por   la otra rama qu estaba implementando  el plugin de reactotron, y  al cambiar la rama no  tomo  el nombre como estaba

2021-07-23 21:09 UTC, sfernandez11 approved these changes
🥇

2021-07-23 21:11 UTC, merged